baseurl = "http://colinlightfoot.com"
disablePathToLower = false
languageCode = "en-us"
title = "Code + Pentesting"
theme = "hugo-octopress"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
# Note it's not under [params] anymore
disqusShortname = "C. Lightfoot"

# Number of blog posts in each pagination page
paginate = 6

# Code highlighting options
# Hugo uses Chroma but names are the same as the old pygments highlighter

# Highlight shortcode and code fences (```) will be treated similarly
pygmentscodefences = true

# Change highlight style here.
# For a full list see: https://xyproto.github.io/splash/docs/all.html
pygmentsStyle = "solarized-dark"

# Other Chroma options can be added here (and in the highlight shortcode in the markdown file)
# See list of supported options: https://gohugo.io/content-management/syntax-highlighting/#options
# for example: pygmentsoptions = "linenos=true"

[permalinks]
post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

[params]

  # --- Start sidebar options ---
  # Number of last posts that will be displayed in the sidebar - set to 0 or remove to hide this section
  sidebarRecentLimit = 5

  # Sidebar header - passed to markdownify so you can write markdown here
  sidebarHeader = "About Me"

  # Sidebar text also supports markdown
  # New lines can be added with </br> or normal markdown (two spaces at the end of line or two new lines).
  # when adding two new lines, remember to remove the indentation otherwise the new line will be treated as a codeblock
  
  sidebarText = """I am a Microsoft consultant by day and explorer by night, learning what I can about
  software development and pentesting. </br>Sometimes I study for certifications, other times I attempt a 
  new project or try to solve a CTF challenge. </br>Whatever I do, though, I'll try my best to share
  it with you."""

  # sidebarText = """Here's a [link to google](https://www.google.com)
  # </br>
  # Second line
  # </br>
  # Third line
  # This line has two spaces in the end to create a new line using markdown
  # Forth line
  # """
  
  
  # Sidebar menu - if true will add a sidebar menu between sidebar text and recent posts
  sidebarMenuEnabled = false
  sidebarMenuHeader = "Interesting Links"

  # sidebar links
  github = "https://github.com/hydure/"
  bitbucket = ""
  twitter = "https://twitter.com/hydure/"
  keybase = ""
  stackoverflow = "https://stackoverflow.com/users/8271155/c-lightfoot"
  linkedin = "https://www.linkedin.com/in/colinflightfoot/"
  googleplus = ""
  youtube = ""
  facebook = "https://www.facebook.com/colin.lightfoot.9"
  instagram = "https://www.instagram.com/hydure"

  # --- End sidebar options ---

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or set to false, then navigation menu links will open in the same window
  navigationNewWindow = true

  # If false, all of blog post will appear on front page (and in pagination)
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Colin Lightfoot"

  # This text appears in the site header under website title
  subtitle = "Showing off the cool things I study."

  # Search engine URL
  searchEngineURL = ""

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Continue Reading &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
   googleAnalytics = "UA-148944050-1"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = false

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  defaultDescription = "Colin Lightfoot's technical blog. I'm sure he's up to something..."

  # Populate this with your own search keywords - these will appear in the meta tags
  defaultKeywords = ["Code" , "Pentesting" , "Interesting" , "Research", "Other"]

  # CSS override files
  # Paths should be relative to the `static` directory
  # customCSS = ["css/custom.css","css/custom2.css"]

  # 404.html header and text - both support markdown
  notFoundHeader = "There's nothing here!"

  notFoundText = """
  Please either go back or use the navigation/sidebar menus. 
  I'm sure you'll find what you're looking for!
  """

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or Set to false to use local fonts
  # remoteFonts = false
  
  # Remove or set to false to use FontAwesome CDN, otherwise the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # Generate taxonomy pages
  generateTaxonomyList = true

  # This is not needed unless alphabetical sort is needed
  # sortTaxonomyAlphabetical = true

  # Twitter card config
  # Enable with this.
  # twitterCardEnabled = true
  # Don't include the @.
  # twitterCardSite = 
  # twitterCardDomain = ""
  # Don't include the @.
  # twitterCardAuthor = ""

  # Set to true to enable compact index. Set to false or remove to go back to classic view.
  # compactIndex = true

# Menu
# If navigationNewWindow (under [params]) is set to true then all links except root ("/") will open in a new window
# If it does not exist or is set to false then links will open in the same window
[[menu.main]]
  Name = "Blog"
  URL = "/"
  weight = -5

[[menu.main]]
  Name = "Archive"
  URL = "/archive/"
  weight = -4

#[[menu.main]]
#  Name = "This theme on Github"
#  URL = "https://www.github.com/parsiya/hugo-octopress"


# Sidebar menus
# Enable with "sidebarMenuEnabled = true" under [params]
# Header text is "sidebarMenuHeader" under [params]
[[menu.sidebar]]
  Name = "Google"
  URL = "https://www.google.com"
  weight = 0

[[menu.sidebar]]
  Name = "Hugo"
  URL = "/categories/hugo/"
  weight = 1

[[menu.sidebar]]
  Name = "Homepage"
  URL = "/"
  weight = 2

# Blackfriday is Hugo's markdown engine. Options are at: https://gohugo.io/overview/configuration/#configure-blackfriday-rendering
[blackfriday]
  hrefTargetBlank = true # open the external links in a new window
  fractions = false

[params.adsense]
client = "ca-pub-4017802261362613"
inArticleSlot = "4017802261362613"